title: jackl.cat
description: Writing, projects, and notes.
url: "https://jackl.cat/"

permalink: /writing/:title/

markdown: kramdown
future: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
