title: jackl.cat
description: Writing, projects, and notes.
url: "https://jackl.cat/"

permalink: /writing/:title/

markdown: kramdown
future: true

collections:
  reading_notes:
    output: true
    permalink: /reading/:name/

defaults:
  - scope:
      path: ""
      type: reading_notes
    values:
      layout: reading-note

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - scripts
